### ISSUE TITLE
Rendering inside the IDE

### ISSUE THREAD

**Issue by miDeb** [Norbert515/flutter_ide#1]
So does this mean that when you change the source code of your app, the IDE needs also to be reloaded? Or how would this work?

**Comment by Norbert515** [comment]
There are multiple ways how this could work. 
What I currently have (and it works pretty well) is that the IDE is just a part of the app. So yes it is also reloaded.

**Comment by TheWithz** [comment]
Being naive on the details, wouldn't reloading the entire IDE chew up a ton of RAM?

**Comment by miDeb** [comment]
This would also mean that the whole IDE runs in debug mode. I don't know how this would impact performance.

**Comment by miDeb** [comment]
AFAIK it's only about assertions(AOT is not supported on desktop, there will always be a vm in JIT mode)

**Comment by Norbert515** [comment]
I don't see why AOT wouldn't be possible. 

Nonetheless, reloading the whole IDE is not an optimal and permanent solution.

Thought about "having runtime access in the IDE" a bit more and I feel like that's not that necessary.
All communication can be done through local servers (like other IDEs do).

Then it would be possible to have the IDE and the actual App as two separate Flutter instances running.

In theory, it should be possible to embed a Flutter view inside another Flutter view (just like it is done with Google Maps and the Web View).

Will explore the idea more at a later point

**Comment by miDeb** [comment]
https://github.com/google/flutter-desktop-embedding/issues/129#issuecomment-425076166:

> flutter build is not capable of making AOT builds for desktop.

>  there's no guarantee that AOT will actually be faster than JIT

**Comment by miDeb** [comment]
Wait... Would it be possible to write a flutter embedder _in flutter_?? (just an idea)

**Comment by Norbert515** [comment]
Haha, that's kinda what we already did :) 
Not Flutter but Dart. More info coming as soon as we sorted out a few things!

**Comment by shareme** [comment]
you guys mean this, there is already an api setup for embedding flutter in dart here
https://github.com/google/flutter-desktop-embedding
