### ISSUE TITLE
No source code available

### ISSUE THREAD

**Issue by gabrc52** [Norbert515/flutter_ide#3]
The provided release seems to be for Windows only, and since there's no source code, it can't be built for Linux, iOS, Android or Mac.

**Comment by zachgrayio** [comment]
Ditto.  Would love to take a look on macos

**Comment by gabrc52** [comment]
I tried to run it with Wine, but it crashed.

**Comment by miDeb** [comment]
@gabrc52 `winehq-staging` worked for me.

**Comment by maks** [comment]
Great start @Norbert515 but I have to say, without any src code I'm yet another possible contributor/user who cannot give you any feedback with your windows only binary build.

There are now 2 maturing desktop embedding project available (apart from your & Simons as yet unpublished desktop embedding) that let us get going with running flutter on "desktop OS's" so if you would like feedback from fellow devs, just publish the src here, no need for us to be given prebuilt exe's.

**Comment by Norbert515** [comment]
@maks totally. I still have a few things to think about (mainly whether I want to keep working on this as an open source project or not), I'll let you know once I figured these things out for myself.
