### ISSUE TITLE
Problem with building in linux

### ISSUE THREAD

**Issue by II11II** [Norbert515/flutter_ide#32]
![image](https://user-images.githubusercontent.com/45257709/81778393-36d07a00-950c-11ea-96bd-94d9b03c173a.png)
**flutter run -d linux** returns error

**Comment by Norbert515** [comment]
Seems like you are on an incompatible Flutter version. What your `flutter doctor` output?

**Comment by II11II** [comment]
@Norbert515 Here 
![image](https://user-images.githubusercontent.com/45257709/82186325-19ccea00-9904-11ea-889b-0b1289d3fbc9.png)

**Comment by hwied** [comment]
I have the same problem, for which version of flutter did your run it @Norbert515 ?
