### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by GabeDottl** [Norbert515/flutter_ide#37]
Hi!

I'm interested in perhaps forking your codebase or using it directly for a project - but it doesn't seem to have a license. Could you add one  (e.g. MIT License) to the README so folks can safely fork?

Thanks!

**Comment by kt-aakash** [comment]
Sure, will do it by 18th of this month

**Comment by Norbert515** [comment]
Hey, of course

Here you go https://github.com/Norbert515/flutter_ide/pull/38 :)
