### ISSUE TITLE
===== CRASH =====

### ISSUE THREAD

**Issue by daVinci13** [Norbert515/flutter_ide#4]
version=2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FFAFCACF4F6
Dumping native stack trace for thread efc
Stack dump aborted because InitialRegisterCheck failed.

**Comment by Norbert515** [comment]
Hey, did you install the C++ runtime files?
If the answer is "yes" then I'm not sure what the problem might be. Remember - this is just an early alpha so stuff will get fixed eventually.

**Comment by daVinci13** [comment]
@Norbert515 Hey, C++ runtime is installed. I understand alpha stage, lots of work to be done. Keep up with awesome work. I'll be watching this repo!
