### ISSUE TITLE
RenderOverflow at "toggle placeholder" widget

### ISSUE THREAD

**Issue by miDeb** [Norbert515/flutter_ide#5]
After finishing the tutorial, this is what I saw:
![bildschirmfoto vom 2019-02-04 14-49-51](https://user-images.githubusercontent.com/44171190/52212274-60700f80-288c-11e9-8067-ec0876f882c3.png)
log:
![bildschirmfoto vom 2019-02-04 14-52-36](https://user-images.githubusercontent.com/44171190/52212381-a2995100-288c-11e9-8fad-e877fc5fa8af.png)
I am using Wine (staging) on Linux Mint Cinnamon 19.1, maybe this does not happen on Windows.

Is my screen too small?

**Comment by Norbert515** [comment]
Yep. That's just a bad layout from my side though. Will be fixed eventually :)
