### ISSUE TITLE
Crash on Starting Widget-marker

### ISSUE THREAD

**Issue by Tembocs** [Norbert515/flutter_ide#6]
Did call `run.bash` and got the following error message.
```
>> bin\dart bin\widget-maker.snapshot
Failed to init NativeSymbolResolver (SymInitialize 87)
flutter: Observatory listening on http://127.0.0.1:49683/

===== CRASH =====
version=2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FFA952CF4F6
Dumping native stack trace for thread 1ff0
Stack dump aborted because InitialRegisterCheck failed.
```

I'm on Windows 10 x64 bit with the C++ redist installed.

**Comment by Norbert515** [comment]
I'm sorry but I'm not sure what the problem might be. I hope future updates will fix this!

**Comment by fg2q1q3q** [comment]
I also encountered the same problem. Here's the error log
> `Failed to init NativeSymbolResolver (SymInitialize 87)
[ERROR:e:\b\build\slave\windows_engine\build\src\flutter\shell\common\engine.cc(112)] Engine run configuration was invalid.
[ERROR:e:\b\build\slave\windows_engine\build\src\flutter\shell\platform\embedder\embedder_engine.cc(61)] Could not launch the engine with configuration.
flutter: Observatory listening on http://127.0.0.1:63015/`
