### ISSUE TITLE
Do you have a version running on mac? I am expecting that 

### ISSUE THREAD

**Issue by ryan730** [Norbert515/flutter_ide#7]
Do you have a version running on mac? I am expecting that

**Comment by gbIxaHue** [comment]
I really want it

**Comment by darmie** [comment]
Can he provide a step guide on how to build this project?

**Comment by Norbert515** [comment]
The IDE folder contains a plain old Flutter project. You can build that for any target you want (Android/iOS/ or Desktop - Mac included using the flutter desktop embedding project)

**Comment by mubasshir** [comment]
+1

**Comment by vinayagg** [comment]
@Norbert515 The IDE folder is not building anymore. 
Since there has not been any update for 4-5 months, are you still working on this?
Even if you are not, can you try once and fix the issues so we can use the work you have done?

**Comment by Norbert515** [comment]
@vinayagg what exactly is the problem?

Due to various reasons (made some wrong assumptions, code therefore got messy etc) I decided to rewrite the IDE and it is now the widget-maker.
Eventually I'd like to incorporate all the ideas I had for this IDE into that!

**Comment by beaniebag** [comment]
Not sure what vinayagg was experiencing exactly, but when I copied the ide contents into flutter's embedded-desktop example project.  I was getting this error for the ColorProperty. 

```
The name 'ColorProperty' is defined in the libraries 'package:flutter/src/painting/colors.dart' and 'package:flutter_visual_builder/widgets/properties/property.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
```

I fixed it by changing 
`import 'package:flutter_visual_builder/widgets/properties/property.dart';`
to
`import 'package:flutter_visual_builder/widgets/properties/property.dart' as VProperty;`
and modified instantiations for example to
`VProperty.ColorProperty (and also the other Properties in this class)`

**Comment by Norbert515** [comment]
Quick update, version 2 will support all operating systems.
