### ISSUE TITLE
Can't run in VM

### ISSUE THREAD

**Issue by MostHated** [Norbert515/flutter_ide#9]
Hey there,
I use Linux and tried to run this in a windows 10 pro virtualbox session but unfortunately received the following. I am guessing it probably just won't work in a VM? I very much am not interested in installing Windows on my PC if I don't have to. 

(I did install the C++ runtime files that were linked)
```
PS C:\Users\mosthated\Downloads\widget-maker\widget-maker-bundled> .\run.bat

C:\Users\mosthated\Downloads\widget-maker\widget-maker-bundled>bin\dart bin\widget-maker.snapshot
Failed to init NativeSymbolResolver (SymInitialize 87)
[ERROR:e:\b\build\slave\windows_engine\build\src\flutter\shell\gpu\gpu_surface_gl.cc(85)] Failed to setup Skia Gr context.
flutter: Observatory listening on http://127.0.0.1:49910/

===== CRASH =====
version=2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF91157BF1C
Dumping native stack trace for thread d74
  [0x00007ff91157bf1c] Unknown symbol
  [0x00007ff91157bf1c] Unknown symbol
-- End of DumpStackTrace
PS C:\Users\mosthated\Downloads\widget-maker\widget-maker-bundled>
```

Thanks,
-MH

**Comment by Norbert515** [comment]
Hey, to be honest, I have no idea what's going wrong.

I'm working on version 2 right now though and it will run on all operating systems (so you won't need a VM).

Hope that helps

**Comment by MostHated** [comment]
Ah, that is great news. Any rough estimate on that? Few weeks, months?

**Comment by Norbert515** [comment]
I'm planning on releasing a version in a couple of weeks :)

**Comment by MostHated** [comment]
Awesome. I will keep an eye out for it. I just started with Flutter/Dart 2-3 days ago, so it would definitely be nice to have something like this in which I can have the visual and then directly see the code it creates.

**Comment by MostHated** [comment]
Quick update to this. It looks like when people get this error when using certain android emulators, a workaround was running  "flutter run --enable-software-rendering" I tried to see if I could append that to the bat command by running  bin\dart bin\widget-maker.snapshot --enable-software-rendering but got the error of:

Unhandled exception:
FormatException: Could not find an option named "enable-software-rendering".

Perhaps if you were to somehow make it so that enabling software rendering in the IDE is possible, it might be able to be used in a Windows VM. Might be worth a shot?

Thanks,
-MH

**Comment by MostHated** [comment]
Was V2 ever released? In the releases tab I only see one from Feb 3, 2019.

**Comment by Norbert515** [comment]
Haven't gotten around updating the releases yet - will do that once I have done some refactoring
